Controllers/FriendsController.cs
using System.Text;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MvcSocial.Models;
using NuGet.Protocol;

namespace MvcSocial.Controllers;

[Authorize(Roles = "Admin,User")]
public class FriendsController : Controller
{
    private readonly IUserRepository _userRepository = UserRepository.Instance;


    private User CurrentUser()
    {
        var loggedUser = HttpContext.User.Identity?.Name;
        if (loggedUser == null)
            throw new ApplicationException("Nobody is currently logged in");
        
        return _userRepository.Users.Find(u => u.Login == loggedUser) 
               ?? throw new ApplicationException("Nobody is currently logged in");
    }
        public IActionResult Index()
        {
            return View(CurrentUser().Friends);
        }

        public IActionResult List()
        {
            return Json(Json(CurrentUser().Friends.Select(f => f.Login)));
        }
        
        
        [ValidateAntiForgeryToken]
        public IActionResult Add(string? login)
        {
            var user = _userRepository.Users.Find(u => u.Login == login);
            if (user == null)
                return Json(false);
            
            CurrentUser().Friends.Add(user);
            return Json(true);
        }
        
        public IActionResult Del(string? id)
        {
            if (id == null)
                return Json(false);

            var user = _userRepository.Users
                .FirstOrDefault(m => m.Login == id);
            if (user == null)
                return Json(false);
            
            CurrentUser().Friends.Remove(user);
            return Json(true);
        }

    public IActionResult Export()
    {
        var bytes = System.Text.Encoding.UTF8.GetBytes(CurrentUser().Friends.Select(f => f.Login).ToJson() ?? "");
        var content = new System.IO.MemoryStream(bytes);
        return File(content , "application/json", "friends.json");
    }

    public IActionResult Import(IFormFile? file)
    {
        if (file == null)
            return RedirectToAction(nameof(Index));
        
        
        var json = new StreamReader(file.OpenReadStream()).ReadToEnd();
        var logins = json.FromJson<List<string>>();

        CurrentUser().Friends = logins.Select(login => _userRepository.Users.Find(u => u.Login == login)).OfType<User>().ToList();
        return RedirectToAction(nameof(Index));
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcSocial</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcSocial.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcSocial</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">@Localizer["Home"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">@Localizer["Privacy"]</a>
                        </li>
                        @if (User.Identity?.IsAuthenticated ?? false) {
                            @if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">@Localizer["Users"]</a>
                                </li>
                            }
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Friends" asp-action="Index">@Localizer["Friends"]</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">@Localizer["Logout"]: @User.Identity.Name</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MvcSocial - <a asp-area="" asp-controller="Home" asp-action="Privacy">@Localizer["Privacy"]</a>
            @await Html.PartialAsync("_SelectLanguagePartial")
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_SelectLanguagePartial.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Localization
@using Microsoft.Extensions.Options

@inject IOptions<RequestLocalizationOptions> LocOptions

@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName })
        .ToList();
}

<div title="@Localizer["Request culture provider:"] @requestCulture?.Provider?.GetType().Name">
    <form id="selectLanguage" asp-controller="Home" asp-action="SetLanguage" asp-route-returnUrl="@Context.Request.Path" method="post" class="form-horizontal" role="form">
        @Localizer["Language"]: <select name="culture" asp-for="@requestCulture.RequestCulture.UICulture.Name" asp-items="cultureItems"></select>
        <input type="submit" value="@Localizer["Update"]" class="btn btn-danger" />
    </form>
</div>